### ISSUE TITLE
Add documentation in Esperanto language

### ISSUE THREAD

**Issue by tnsc** [apalaciosdev/ngx-forms-validator#1]
Dankon

**Comment by apalaciosdev** [comment]
[here it is! ](https://acortar.link/TjL1CC)✔

**Comment by tnsc** [comment]
Ĝi ne estas tio, kion mi serĉis, sed mi pensas, ke ĝi povas helpi min. Koran dankon junuloj! Dio benu vin, mi estos eterne dankema! 
![image](https://media1.tenor.com/m/e8O3ysG8kHMAAAAC/dance-dancing.gif)
